#! /bin/bash

if [[ -z "$BROWSER" ]]; then
	echo "Set BROWSER environment variable to specify browser.  Using default."
fi

MARA_LOG=true SAVE_AND_OPEN_PAGE=false DRIVER_NAME=Mara.Drivers.WebDriver nunit-color-console bin/Debug/Mara.Specs.dll
